import { requireAuth } from "@/lib/auth/session";
import { getStyleGuide, autoGenerateStyleGuide } from "@/lib/clientes/marca-actions";
import { MarcaForm } from "@/components/clientes/MarcaForm";
import { Card } from "@/components/ui/card";

function isEmpty(guide: object): boolean {
  return Object.values(guide).every((v) => !v);
}

export default async function MarcaPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  await requireAuth();
  let initial = await getStyleGuide(id);

  let autoGenerated = false;
  if (isEmpty(initial)) {
    initial = await autoGenerateStyleGuide(id);
    autoGenerated = !isEmpty(initial);
  }

  return (
    <Card className="p-5">
      <div className="mb-4">
        <h2 className="text-lg font-semibold">Identidade visual</h2>
        <p className="text-xs text-muted-foreground">
          Cores, fontes e estilo do cliente. A IA usa esses dados pra gerar artes mais fiéis à marca.
        </p>
        {autoGenerated && (
          <p className="mt-2 text-xs text-amber-600 dark:text-amber-400">
            Preenchido automaticamente pela IA com base nos dados do cliente. Revise e ajuste conforme necessário.
          </p>
        )}
      </div>
      <MarcaForm clientId={id} initial={initial} />
    </Card>
  );
}
